name: Docker
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Set the VERSION
        run: echo "::set-env name=VERSION::${GITHUB_REF##*/}"
        if: github.ref != 'refs/heads/master'
      - name: Build
        run: docker-compose build
      - name: Test
        run: docker-compose run --rm sodium-bot start --session-id=sodium -t 180 https://www.youtube.com/watch?v=mY6sChi65oU
      - name: Push
        run: docker-compose push
