name: Docker
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  docker-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Set the VERSION
        run: echo "VERSION=${GITHUB_REF##*/}" >> "${GITHUB_ENV}"
        if: github.ref != 'refs/heads/master'
      - name: Build
        run: docker compose build
      - name: Test
        run: docker compose run --rm sodium-bot start --session-id=sodium -t 180 https://www.youtube.com/watch?v=mY6sChi65oU
      - name: Push
        run: docker compose push
